### ISSUE TITLE
update.sh does not delete old files

### ISSUE THREAD

**Issue by and1truong** [acquia/lightning-features#54]
Should we use `rsync` with `--delete` flag instead of `cp`?

https://github.com/acquia/lightning-features/blob/7.x-1.x/update.sh

**Comment by saltednut** [comment]
That would probably work. Do you have a PR?

**Comment by zanami** [comment]
rsync: --delete does not work without --recursive (-r) or --dirs (-d).
rsync error: syntax or usage error (code 1) at main.c(1453) [client=3.0.9]

# cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian

Update downloads everything then fires 2 rsync errors and then removes what it's downloaded.

**Comment by saltednut** [comment]
@zanami thanks for this report. I believe this is resolved again but I'll leave to you to confirm.
